In [1]:
import numpy as np

## Numpy vs Lists

In [ ]:
height = [74, 75, 72, 71]

In [3]:
cp_arr_1 = np.random.randint(10, size=(2, 2))
print(f"cp_arr_1:\n {cp_arr_1}")
cp_arr_2 = cp_arr_1
print(f"cp_arr_2:\n {cp_arr_2}")

cp_arr_1:
 [[8 1]
 [3 6]]
cp_arr_2:
 [[8 1]
 [3 6]]


In [5]:
# If we can change anything in object then, that's change will reflect into other object as welll
cp_arr_1[0,0] = 2
print(f"cp_arr_1:\n {cp_arr_1}")
print(f"cp_arr_2:\n {cp_arr_2}")

cp_arr_1:
 [[2 1]
 [3 6]]
cp_arr_2:
 [[2 1]
 [3 6]]


In [6]:
cp_arr_3 = cp_arr_1.view()
cp_arr_3.flatten('F')
print(f"cp_arr_2:\n {cp_arr_2}")

cp_arr_2:
 [[2 1]
 [3 6]]


In [7]:
cp_arr_4 = cp_arr_1.copy()
print(f"cp_arr_4:\n {cp_arr_4}")

cp_arr_4:
 [[2 1]
 [3 6]]


In [9]:
if cp_arr_1 is cp_arr_2:
    print("Both Object are same")
else:
    print("Both object are not same")

Both Object are same


In [10]:
if cp_arr_1 is cp_arr_4:
    print("Both Object are same")
else:
    print("Both object are not same")

Both object are not same
