In [1]:
import numpy as np

In [2]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_m_arr_1 = np.array(m_list_1)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np_m_arr_1.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
np.resize(np_m_arr_1,(2,5))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [9]:
np_m_arr_1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
np_m_arr_1.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
# Flaten on Row order
np_m_arr_1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Flaten on Column order
np_m_arr_1.flatten('F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [16]:
np_m_arr_1.sort(axis=0)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])