In [2]:
import numpy as np

In [3]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([2,4,6,8])

In [4]:
# Addition
arr_1+ arr_2

array([ 3,  6,  9, 12])

In [5]:
# Substraction
arr_1-arr_2

array([-1, -2, -3, -4])

In [6]:
# Multiplication
arr_1*arr_2

array([ 2,  8, 18, 32])

In [7]:
# Divide
arr_1/arr_2

array([0.5, 0.5, 0.5, 0.5])

In [8]:
arr_3 = np.random.randint(100, size=(4))
arr_4 = np.random.randint(100, size=(2,3))
arr_5 = np.random.randn(4)
arr_6 = np.random.choice(arr_3)
arr_6

np.int32(3)

In [9]:
print(arr_4)
print(arr_4.sum(axis=0))
print(arr_4.cumsum(axis=1))

[[76 40 24]
 [ 1 96 88]]
[ 77 136 112]
[[ 76 116 140]
 [  1  97 185]]


In [10]:
print(arr_4.min())
print(arr_4.min(axis=0))

1
[ 1 40 24]


In [11]:
print(arr_4.max())
print(arr_4.max(axis=1))

96
[76 96]


In [22]:
# Add constant into the array
print(arr_4)
np.add(arr_4, 5) 

[[78 47 40]
 [59 66 77]]


array([[83, 52, 45],
       [64, 71, 82]])

In [25]:
np.add(arr_4, arr_4) 

array([[156,  94,  80],
       [118, 132, 154]])

In [26]:
np.subtract(arr_4, arr_4) 

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.multiply(arr_4, arr_4) 

array([[6084, 2209, 1600],
       [3481, 4356, 5929]])

In [28]:
np.divide(arr_4, arr_4) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr_7 = np.array([[1,2],[3,4]])
arr_8 = np.array([[2,4],[6,9]])
np.remainder(arr_7, arr_8)

array([[1, 2],
       [3, 4]])

In [30]:
np.power(arr_7, arr_8)

array([[     1,     16],
       [   729, 262144]])

In [31]:
np.sqrt(arr_8)

array([[1.41421356, 2.        ],
       [2.44948974, 3.        ]])

In [32]:
np.cbrt(arr_8)

array([[1.25992105, 1.58740105],
       [1.81712059, 2.08008382]])

In [33]:
np.absolute([-1, -2])

array([1, 2])

In [34]:
np.exp(arr_8)

array([[7.38905610e+00, 5.45981500e+01],
       [4.03428793e+02, 8.10308393e+03]])

In [36]:
np.exp2(arr_8)

array([[  4.,  16.],
       [ 64., 512.]])

In [37]:
np.log(arr_7)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [38]:
np.log10(arr_7)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [40]:
# Lowest common Divider
np.gcd.reduce([9,12,15,18])

3

In [41]:
# Lowest common modable(LCM)
np.lcm.reduce([9,12,15,18])

180

In [44]:
# Rounging up with lowest value
np.floor([1.2,1.5,5])

array([1., 1., 5.])

In [45]:
# Rounging up with highest value
np.ceil([1.2,3.1,5.0])

array([2., 4., 5.])

In [52]:
sq_arr = np.arange(6) ** 2
sq_arr

array([ 0,  1,  4,  9, 16, 25])

In [53]:
arr_9 = np.random.randint(10, size=(5, 3))
print(arr_9)
mc_index = arr_9.argmax(axis=1)
mc_index

[[5 2 2]
 [0 5 4]
 [2 3 6]
 [0 8 6]
 [5 8 1]]


array([0, 1, 2, 1, 1], dtype=int64)

In [54]:
max_nums = arr_9[mc_index]
max_nums

array([[5, 2, 2],
       [0, 5, 4],
       [2, 3, 6],
       [0, 5, 4],
       [0, 5, 4]])