In [15]:
import numpy as np
from numpy import linalg as LA

In [16]:
arr_1 = np.array([[5,6],[7,8]])
arr_2 = np.array([[1,2],[3,4]])
arr_3 = np.array([[2,4],[6,9]])

In [17]:
# Matrix multiplication with Dot Product
# (1 * 2) + (2 * 6) = 14 [0,0]
# (1 * 4) + (2 * 9) = 22 [0,1]
# (3 * 2) + (4 * 6) = 30 [1,0]
# (3 * 4) + (4 * 9) = 12 + 36 = 48 [1,1]
np.dot(arr_2, arr_3)
# if we need to perform dot product on multiple array
LA.multi_dot([arr_1, arr_2, arr_3])

array([[250, 398],
       [338, 538]])

In [18]:
# Matrix multiplication with Inner Product
# (1 * 2) + (2 * 4) = 10 [0,0]
# (1 * 6) + (2 * 9) = 24 [0,1]
# (3 * 2) + (4 * 4) = 22 [1,0]
# (3 * 6) + (4 * 9) = 54 [1,1]
np.inner(arr_1, arr_2)

array([[17, 39],
       [23, 53]])

In [19]:
# Matrix multiplication with Tensor Dot Product
# (1 * 1) + (2 * 1) + (3 * 3) + (4 * 4) = 30 [0,0]
# (5 * 1) + (6 * 2) + (7 * 3) + (8 * 4) = 

arr_4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr_5 = np.array([[1,2],[3,4]], dtype=object)
np.tensordot(arr_4, arr_5)

array([30, 70], dtype=object)

In [20]:
#Einstein Summation: Provides many ways to perform
# operations on multiple arrays

arr_6 = np.array([0,1])
arr_7 = np.array([[0,1,2,3],[4,5,6,7]])

#'i,ij->i'


np.einsum('i,ij->i', arr_6, arr_7)

array([ 0, 22])

In [21]:
# Raise matrix to the power of n
# Given [[a,b], [c,d]]
# [[a^2 + bc, ab + db], [ac + dc, d^2 + bc]]

LA.matrix_power(arr_5, 2)

array([[7, 10],
       [15, 22]], dtype=object)

In [22]:
# Kronecker product of 2 arrays
# Given [[a,b], [c,d]], [[e,f], [g, h]]
# [[a*e, a*f, b*e, b*f], [a*g, a*h, b*g, b*h], ...]

np.kron(arr_5, arr_6)

array([[0, 1, 0, 2],
       [0, 3, 0, 4]], dtype=object)

In [27]:
# Compute eigenvalues
LA.eig(arr_4)

LA.eigvals(arr_4)

array([[-0.37228132,  5.37228132],
       [-0.15206735, 13.15206735]])

In [28]:
# Gen Vector Norm sqrt(sum(X**2))

LA.norm(arr_5)

5.477225575051661

In [30]:
# Get Multiplicative Inverse of a matrix
LA.inv(arr_4)

array([[[-2. ,  1. ],
        [ 1.5, -0.5]],

       [[-4. ,  3. ],
        [ 3.5, -2.5]]])

In [31]:
# Get Condition Number matrics
LA.cond(arr_4)

array([14.93303437, 86.98850423])

In [36]:
# Determinates are used to compute values, area, to solve systems
# of equations and more. It is a way you 
# matrix to get 1 number.
# For a matrix to have an inverse its determinate must not equal 0
# det([[a,b],[c,d]]) = a*d - b*c

arr_8 = np.array([[1,2],[3,4]])
LA.det(arr_8) # 1*4 - 2*3 = -2


-2.0000000000000004

In [38]:
# Determinate of 3x3 Matrix
# def([[a,b,c], [d,e,f], [g,h,i]]) = a*e*i - b*d*i + c*d*h
# -a*f*h + b*f*g - c*e*g

arr_8_i = LA.inv(arr_8)
arr_8_i
np.dot(arr_8, arr_8_i)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [40]:
# Solving systems of Linear Equations
# If you have 3X + 5 = 9X -> 5 = 6X -> x = 5/6
# If you have x + 4y = 10 & 6x + 18y = 42
# Isolate x -> x =10 -4Y
# 6(10 - 4y) + 18y = 42 -> 60 - 24y + 18y = 42 -> -6y = -18 -> y =3
# x + 4*3 = 10 -> x = -2

arr_9 = np.array([[1,4], [6, 18]])
arr_10 = np.array([10,42])
LA.solve(arr_9, arr_10)

array([-2.,  3.])

In [41]:
# Return a identity matrix with defined number of rows and columns

np.eye(2,2, dtype=int)

array([[1, 0],
       [0, 1]])