In [1]:
import numpy as np

In [2]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_m_arr_1 = np.array(m_list_1)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np_m_arr_1[0, 0]= 2
np_m_arr_1.itemset((0, 1), 1)
np_m_arr_1

array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np_m_arr_1.shape

(3, 3)

In [6]:
# Fetch the data from array
print(np_m_arr_1[0,1])
print(np_m_arr_1.item(0,1))

1
1


In [7]:
# Get the value from the array
np.take(np_m_arr_1, [0, 3, 6])

array([2, 4, 7])

In [8]:
# Put value into the Array
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [9]:
np_m_arr_1[:5:2]

array([[10,  1,  3],
       [10,  8,  9]])

In [11]:
np_m_arr_1[:,2]

array([3, 6, 9])

In [12]:
np_m_arr_1[::-1]

array([[10,  8,  9],
       [10,  5,  6],
       [10,  1,  3]])

In [13]:
evens = np_m_arr_1[np_m_arr_1%2==0]
evens

array([10, 10,  6, 10,  8])

In [14]:
np_m_arr_1[np_m_arr_1>5]

array([10, 10,  6, 10,  8,  9])

In [15]:
np_m_arr_1[(np_m_arr_1>5)&(np_m_arr_1<10)]

array([6, 8, 9])

In [16]:
np.unique(np_m_arr_1)

array([ 1,  3,  5,  6,  8,  9, 10])