In [1]:
import numpy as np

In [5]:
ss_arr_1 = np.random.randint(10, size=(2, 2))
print(f"ss_arr_1:\n {ss_arr_1}")
ss_arr_2 = np.random.randint(10, size=(2, 2))
print(f"ss_arr_2:\n {ss_arr_2}")

ss_arr_1:
 [[1 4]
 [9 5]]
ss_arr_2:
 [[1 9]
 [5 4]]


In [6]:
np.vstack((ss_arr_1, ss_arr_2))

array([[1, 4],
       [9, 5],
       [1, 9],
       [5, 4]])

In [7]:
np.hstack((ss_arr_1, ss_arr_2))

array([[1, 4, 1, 9],
       [9, 5, 5, 4]])

In [9]:
# Deleting data into the array
ss_arr_3 = np.delete(ss_arr_1, 1, 0)
print(f"Deleting ss_arr_3 Array : \n {ss_arr_3}")
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print(f"Deleting ss_arr_4 Array : \n {ss_arr_4}")

Deleting ss_arr_3 Array : 
 [[1 4]]
Deleting ss_arr_4 Array : 
 [[1 9]]


In [11]:
# Column Stack
np.column_stack((ss_arr_3, ss_arr_4))

array([[1, 4, 1, 9]])

In [12]:
# Row Stack
np.row_stack((ss_arr_3, ss_arr_4))

array([[1, 4],
       [1, 9]])

In [14]:
ss_arr_5 = np.random.randint(10, size=(2, 10))
print(f"ss_arr_5:\n {ss_arr_5}")
np.hsplit(ss_arr_5, 5)

ss_arr_5:
 [[7 4 8 6 3 2 2 9 4 6]
 [2 8 0 7 5 8 5 4 2 4]]


[array([[7, 4],
        [2, 8]]),
 array([[8, 6],
        [0, 7]]),
 array([[3, 2],
        [5, 8]]),
 array([[2, 9],
        [5, 4]]),
 array([[4, 6],
        [2, 4]])]

In [15]:
np.hsplit(ss_arr_5, (2, 4))

[array([[7, 4],
        [2, 8]]),
 array([[8, 6],
        [0, 7]]),
 array([[3, 2, 2, 9, 4, 6],
        [5, 8, 5, 4, 2, 4]])]