In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

In [3]:
list_1 = [1,2,3,4,5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [4]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_m_arr_1 = np.array(m_list_1)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(np.arange(1, 10))

print(np.arange(1, 10, 3))

print(np.linspace(0,5,5))

print(np.zeros(3))

print(np.zeros((2,3)))

print(np.ones(3))

print(np.ones((2,3)))

[1 2 3 4 5 6 7 8 9]
[1 4 7]
[0.   1.25 2.5  3.75 5.  ]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
np_arr_2 = np.array([1,2,3,4,5,6])
np_arr_2.dtype

dtype('int32')

#### Data Type in NumPy

Boolean: np.bool

Char: np.byte

Short : np.short

Integer : np.short

Long : np.int_

Float : np.single & np.float32

Double : np.double & np.float64

np.int8 : -128 tp 127

np.int16 : -32768 to 32767

np.int32 : -2147483648 to 2147483647

np.int64 : -9223372036854775808 to 9223372036854775807

In [14]:
print(np.random.randint(10, 50, 5))
print(np.random.randint(10, 50, size=(2,3)))

[15 20 41 37 28]
[[10 32 17]
 [28 10 23]]


In [15]:
# Know about the Doc
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp