In [1]:
import numpy as np

In [2]:
carr_1 = np.array([2,3])
carr_2 = np.array([3,2])

In [3]:
np.greater(carr_1, carr_2)

array([False,  True])

In [4]:
np.greater_equal(carr_1, carr_2)

array([False,  True])

In [5]:
np.less_equal(carr_1, carr_2)

array([ True, False])

In [6]:
np.not_equal(carr_1, carr_2)

array([ True,  True])

In [7]:
np.equal(carr_1, carr_2)

array([False, False])